blank_issues_enabled: false
contact_links:
  - name: CONTIBUTING.md
    url: https://github.com/kisvegabor/abbreviations-in-code/blob/master/.github/CONTRIBUTING.md
    about: The basic rules of contributing
